void h(){
    Miss
    case1:
    "inline//\\extern"
    case2:
    "const||char"
    case3:
    "BigInt&&float"
    case4:
    "const\\extern"
    case5:
    "char&&inline"
    case6:
    "float//BigInt"
    case7:
    "char\\\\&extern"
    case8:
    "const&////inline"
    case9:
    "Float&\\//&BigInt"
}
